#!/bin/bash

# Note: Before running this script:
#  0) NodeMCU must be installed
#  1) The ESP8266 must be accessible via the serial port
#  2) No script should be running
#  3) The serial connection must be disconnected

# Upload settings script (hand-written or generated by generate-settings.sh)
./upload.sh settings.lua

# Upload init script
./upload.sh src/init.lua

# Upload sensor script
./upload.sh src/read-rht03.lua

# Upload main script
./upload.sh src/main-rht03.lua
